# Generated by Django 2.1.1 on 2018-09-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='short',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
