# Generated by Django 2.1.1 on 2018-10-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short',
        ),
    ]
